config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "profiles#index"

  resources :profiles do
    resources :packages
    resources :albums
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photos
  accepts_nested_attributes_for :photos
end

app/models/category.rb
class Category < ActiveRecord::Base

end

app/models/package.rb
class Package < ActiveRecord::Base
  belongs_to :profile

  validates :title, presence: true
  validates :details, presence: true
  validates :price, presence: true

  def package_owner_or_admin?(logged_in_user)
    profile.user == logged_in_user || logged_in_user.admin
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :albums
  has_many :photos, through: :albums
  has_many :packages
  has_many :categories

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :location, presence: true
  validates :years_experience, presence: true
  validates :user_id, presence: true

  mount_uploader :avatar, AvatarUploader

  searchable do
    string :first_name
    string :last_name
    string :location
    string :median_price
    integer :category_id, :multiple => true

    text :title, :body
    text :comments do
      comments.map { |comment| comment.body }
    end
  end

  def owner_or_admin?(logged_in_user)
    if logged_in_user == nil
      return false
    elsif user == logged_in_user || logged_in_user.admin
      return true
    end
  end

  def username
    return first_name + " #{last_name[0]}."
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController

  def new
    @profile = Profile.find(params[:profile_id])
    @package = Package.new
  end

  def create
    @package = Package.new(package_params)
    # binding.pry
    @package.profile = Profile.find(params[:profile_id])
    if @package.save
      flash[:notice] = "Package Saved"
      redirect_to profile_path(@package.profile)
    else
      flash[:notice] = "Invalid Input"
      render :new
    end
  end

  def edit
    access_to_package?(current_user)
  end

  def update
    access_to_package?(current_user)
    if @package.update(package_params)
      flash[:notice] = "Package information updated"
      redirect_to profile_path(@profile)
    else
      flash[:notice] = "Invalid package submission"
      render :edit
    end
  end

  def destroy
    access_to_package?(current_user)
    if @package.destroy
      flash[:notice] = "Package sucessfully deleted"
      redirect_to profile_path(@profile)
    else
      flash[:notice] = "Package was not deleted"
    end
  end

  def access_to_package?(current_user)
    package = Package.find(params[:id]).profile.user.id
    if current_user.admin || current_user.id == package
      @package = Package.find(params[:id])
      @profile = Profile.find(params[:profile_id])
    else
      flash[:notice] = "You do not have access to this profile"
      redirect_to root_path
    end
  end

  protected
  def package_params
    params.require(:package).permit(:title, :details, :price, :package_id)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  mount_uploader :photo, AvatarUploader
  belongs_to :album

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @profiles = Profile.page(params[:page])
  end

  def show
    @profile = Profile.find(params[:id])
    @packages = Package.where(profile_id: params[:id])
  end

  def new
    has_profile?(current_user)
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    if @profile.save
      flash[:notice] = "profile Saved"
      redirect_to profile_path(@profile)
    else
      flash[:notice] = "Invalid Input"
      render :new
    end
  end

  def edit
    access_to_profile?(current_user)
  end

  def update
    access_to_profile?(current_user)
    if @profile.update(profile_params)
      flash[:notice] = "Profile information updated"
      redirect_to profile_path
    else
      flash[:notice] = "Invalid profile submission"
      render :edit
    end
  end

  def destroy
    access_to_profile?(current_user)
    if @profile.destroy
      flash[:notice] = "Profile successfully deleted"
      redirect_to root_path
    else
      flash[:notice] = "Profile was not deleted"
    end
  end

  def access_to_profile?(current_user)
    profile = Profile.find(params[:id]).user.id
    if current_user.admin || current_user.id == profile
      @profile = Profile.find(params[:id])
    else
      flash[:notice] = "You do not have access to this profile"
      redirect_to root_path
    end
  end

  def has_profile?(current_user)
    @profile = Profile.where(user_id: current_user)
    if @profile != []
      redirect_to profile_path(@profile[0].id)
    else
      @profile = Profile.new
    end
  end

  protected
  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :location,
      :years_experience, :user_id, :avatar)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HotShots</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<nav class="navbar navbar-trans navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapsible">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand text-danger" href="/">HotShots</a>
    </div>
    <div class="navbar-collapse collapse" id="navbar-collapsible">
      <ul class="nav navbar-nav navbar-left">
        <li><a href="#section1">Search</a></li>
        <li><a href="#section2">Next</a></li>
        <li><a href="#section3">Then</a></li>
        <li><a href="#section4">Form</a></li>
        <li><a href="#section5">More</a></li>
        <li><a href="#section6">Last</a></li>
        <li>&nbsp;</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%- if current_user -%>
          <li><%= link_to 'My Profile', new_profile_path(current_user) %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete,  class: "button radius" %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path,  class: "button radius" %></li>
          <li><%= link_to 'Sign In', new_user_session_path,  class: "button radius" %></li>
        <%- end -%>
      </ul>
    </div>
  </div>
</nav>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/profiles/_form.html.erb
<%= form_for @profile, :html => {:multipart => true} do |f| %>

  <%= f.label :first_name %>:
  <%= f.text_field :first_name %><br />

  <%= f.label :last_name %>:
  <%= f.text_field :last_name %><br />

  <%= f.label :location %>:
  <%= f.text_field :location %><br />

  <%= f.label :years_experience %>:
  <%= f.number_field :years_experience %><br />

  <%= f.label :portfolio_website %>:
  <%= f.text_field :portfolio_website %><br />

  <%= f.label :avatar %>:
  <%= f.file_field :avatar %><br />

  <%= f.submit "Create Profile" %>

<% end %>

app/views/profiles/edit.html.erb
<%= render 'form' %>

app/views/profiles/index.html.erb
<div class="row">
  <div class="col-lg-offset-1 index-container">
  <% @profiles.each do |profile| %>
    <div class="col-lg-2 panel image-panel">
      <div class="row">
        <%= image_tag("test_photo.jpg", width:"100%")%>
      </div>
      <div class="row index-panel">
        <div class="col-lg-2">
          <%= image_tag profile.avatar.small_thumb.url.to_s %>
        </div>
        <div class="col-lg-4">
        <%= link_to profile.username, profile %>
        </div>
        <div class="col-lg-4">
        this
        </div>
        </div>
    </div>
  <% end %>
  </div>
</div>

app/views/profiles/new.html.erb
<%= render 'form' %>

app/views/profiles/show.html.erb
<%= image_tag @profile.avatar.thumb.url.to_s %>


<h3><%= @profile.username %></h3>

<p><%= @profile.location %></p>
<p>Years of experience: <%= @profile.years_experience %></p>
<p>Portfolio: <%= @profile.portfolio_website %></p>

<%- if @profile.owner_or_admin?(current_user)%>
  <p><%= link_to "Edit Profile", edit_profile_path(@profile) %></p>
  <p><%= link_to "Delete Profile", profile_path(@profile), method: :delete %></p>
  <p><%= link_to "New Package", new_profile_package_path(@profile) %></p>
  <% else%>
<% end %>

<h3>Packages</h3>
<% @packages.each do |package| %>
  <p><%= package.title %></p>
  <% if current_user %>
    <% if package.package_owner_or_admin?(current_user) %>
      <p><%= link_to "Edit Package", edit_profile_package_path(@profile, package) %></p>
      <p><%= link_to "Delete Package", profile_package_path(@profile, package), method: :delete %></p>
    <% end %>
  <% end %>
<% end %>